
export const INDUSTRIES = [
  "ICT / Technology",
  "Banking & Finance",
  "Oil & Gas",
  "Manufacturing",
  "Healthcare",
  "Construction & Engineering",
  "Government / Public Service",
  "Education",
  "Agriculture",
  "Telecommunications",
  "Retail & Commerce",
  "Media & Communications",
  "Law",
  "Accounting & Audit",
  "Other",
] as const;

export const LEVELS = [
  "100 Level",
  "200 Level",
  "300 Level",
  "400 Level",
  "500 Level",
  "HND 1",
  "HND 2",
  "Postgraduate",
] as const;

export const WEEKDAYS = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
] as const;

export const POPULAR_UNIVERSITIES = [
  // ── Federal Universities ──────────────────────────────────────────────────
  "Abubakar Tafawa Balewa University, Bauchi (ATBU)",
  "Ahmadu Bello University, Zaria (ABU)",
  "Alex Ekwueme Federal University, Ndufu-Alike (AE-FUNAI)",
  "Bayero University, Kano (BUK)",
  "Federal University of Agriculture, Abeokuta (FUNAAB)",
  "Federal University of Agriculture, Makurdi (FUAM)",
  "Federal University of Petroleum Resources, Effurun (FUPRE)",
  "Federal University of Technology, Akure (FUTA)",
  "Federal University of Technology, Minna (FUTMinna)",
  "Federal University of Technology, Owerri (FUTO)",
  "Federal University, Birnin Kebbi (FUBK)",
  "Federal University, Dutsinma (FUDMA)",
  "Federal University, Gusau (FUG)",
  "Federal University, Kashere (FUKASHERE)",
  "Federal University, Lafia (FULAFIA)",
  "Federal University, Lokoja (FULOKOJA)",
  "Federal University, Otuoke (FUO)",
  "Federal University, Oye-Ekiti (FUOYE)",
  "Federal University, Wukari (FUWUKARI)",
  "Godfrey Okoye University, Enugu (GOUNI)",
  "Modibbo Adama University of Technology, Yola (MAUTECH)",
  "National Open University of Nigeria, Lagos (NOUN)",
  "Nile University of Nigeria (NUN)",
  "Nnamdi Azikiwe University, Awka (UNIZIK)",
  "Obafemi Awolowo University, Ile-Ife (OAU)",
  "Umaru Musa Yar'adua University, Katsina (UMYU)",
  "University of Abuja (UNIABUJA)",
  "University of Calabar (UNICAL)",
  "University of Ibadan (UI)",
  "University of Ilorin (UNILORIN)",
  "University of Jos (UNIJOS)",
  "University of Lagos (UNILAG)",
  "University of Maiduguri (UNIMAID)",
  "University of Nigeria, Nsukka (UNN)",
  "University of Port Harcourt (UNIPORT)",
  "University of Uyo (UNIUYO)",
  "Usmanu Danfodiyo University, Sokoto (UDUS)",
  // ── State Universities ────────────────────────────────────────────────────
  "Abia State University (ABSU)",
  "Adamawa State University (ADSU)",
  "Akwa Ibom State University (AKSU)",
  "Anambra State University of Science and Technology (ANSU)",
  "Bauchi State University (BASU)",
  "Bayelsa State University (BAYSU)",
  "Benue State University (BSU)",
  "Borno State University (BOSU)",
  "Cross River State University (CRSU)",
  "Delta State University (DELSU)",
  "Ebonyi State University (EBSU)",
  "Edo State University (EDSU)",
  "Ekiti State University (EKSU)",
  "Enugu State University of Science and Technology (ESUT)",
  "Gombe State University (GSU)",
  "Imo State University (IMSU)",
  "Jigawa State University (JSU)",
  "Kaduna State University (KASU)",
  "Kano State University (KASU-K)",
  "Katsina State University (KSU)",
  "Kebbi State University of Science and Technology (KSUSTA)",
  "Kogi State University (KSU-K)",
  "Kwara State University (KWASU)",
  "Lagos State University (LASU)",
  "Lagos State University of Science and Technology (LASUSTECH)",
  "Nasarawa State University (NSUK)",
  "Niger State University (NSUK-N)",
  "Ogun State University (OSU)",
  "Ondo State University (UNIMOSA)",
  "Osun State University (UNIOSUN)",
  "Oyo State University (OYSU)",
  "Plateau State University (PLASU)",
  "Rivers State University (RSU)",
  "Sokoto State University (SSU)",
  "Taraba State University (TASU)",
  "Yobe State University (YSU)",
  "Zamfara State University (ZSU)",
  // ── Federal Polytechnics ──────────────────────────────────────────────────
  "Auchi Polytechnic (AUCHI POLY)",
  "Federal Polytechnic, Ado-Ekiti (FEPAD)",
  "Federal Polytechnic, Bauchi (FEPOBA)",
  "Federal Polytechnic, Bida (FEPOB)",
  "Federal Polytechnic, Daura (FEPODAR)",
  "Federal Polytechnic, Ekiti (FEPOE)",
  "Federal Polytechnic, Ilaro (ILAROPOLY)",
  "Federal Polytechnic, Kaura Namoda (FEPOKN)",
  "Federal Polytechnic, Mubi (FEPOM)",
  "Federal Polytechnic, Nasarawa (FEPON)",
  "Federal Polytechnic, Offa (OFFAPOLY)",
  "Federal Polytechnic, Oko (FEPO)",
  "Federal Polytechnic, Oshogbo (FEPOSH)",
  "Federal Polytechnic, Potiskum (FEPOP)",
  "Federal Polytechnic, Ugep (FEPOUG)",
  "Federal Polytechnic, Unwana (FEPOUNA)",
  "Federal Polytechnic, Yauri (FEPOYAURI)",
  "Kaduna Polytechnic (KADPOLY)",
  "Moshood Abiola Polytechnic, Abeokuta (MAPOLY)",
  "Petroleum Training Institute, Effurun (PTI)",
  "Port Harcourt Polytechnic (PHP)",
  "The Polytechnic, Ibadan (POLYIBADAN)",
  "The Polytechnic, Ile-Ife (POLYILEIFE)",
  "Yaba College of Technology (YABATECH)",
  // ── State Polytechnics ────────────────────────────────────────────────────
  "Abia State Polytechnic (ABIAPOLY)",
  "Adamawa State Polytechnic (ADSPOLY)",
  "Akwa Ibom State Polytechnic (AKSPOLY)",
  "Anambra State Polytechnic (ANSPOLY)",
  "Bauchi State Polytechnic (BSPOLY)",
  "Bayelsa State Polytechnic (BAYSPOLY)",
  "Benue State Polytechnic (BEPOLY)",
  "Birnin Kebbi Polytechnic (BKPOLY)",
  "Borno State Polytechnic (BOPOLY)",
  "Cross River State Polytechnic (CRSPOLY)",
  "Delta State Polytechnic (DSPOLY)",
  "Ebonyi State Polytechnic (EBPOLY)",
  "Edo State Polytechnic (EDOPOLY)",
  "Enugu State Polytechnic (ENSPOLY)",
  "Gombe State Polytechnic (GSPOLY)",
  "Imo State Polytechnic (IMOPOLY)",
  "Jigawa State Polytechnic (JSPOLY)",
  "Kaduna State Polytechnic (KADSPOLY)",
  "Kano State Polytechnic (KANOPOLY)",
  "Katsina Polytechnic (KATPOLY)",
  "Katsina State Polytechnic (KATSPOLY)",
  "Kebbi State Polytechnic (KEBPOLY)",
  "Kogi State Polytechnic (KOGIPOLY)",
  "Kwara State Polytechnic (KWAPOLY)",
  "Lagos State Polytechnic (LASUPOLY)",
  "Nasarawa State Polytechnic (NASPOLY)",
  "Niger State Polytechnic (NSPOLY)",
  "Ogun State Institute of Technology (OGITECH)",
  "Ogun State Polytechnic (OGUNPOLY)",
  "Ondo State Polytechnic (ONDOPOLY)",
  "Osun State College of Technology (OSCOTECH)",
  "Osun State Polytechnic (OSPOLY)",
  "Oyo State Polytechnic (OYOPOLY)",
  "Plateau State Polytechnic (PLASPOLY)",
  "Rivers State Polytechnic (RSPOLY)",
  "Sokoto State Polytechnic (SSPOLY)",
  "Taraba State Polytechnic (TASPOLY)",
  "Yobe State Polytechnic (YSPOLY)",
  "Zamfara State Polytechnic (ZSPOLY)",
  // ── Private Universities ──────────────────────────────────────────────────
  "Adeleke University, Osun State (ADELEKE)",
  "Adekunle Ajasin University, Akungba-Akoko (AAUA)",
  "Afe Babalola University, Ado-Ekiti (ABUAD)",
  "Ajayi Crowther University, Ibadan (ACU)",
  "Al-Hikmah University, Ilorin (ALHIKMAH)",
  "Ambrose Alli University, Ekpoma (AAU)",
  "American University of Nigeria, Yola (AUN)",
  "Anchor University, Lagos (ANCHOR)",
  "Babcock University, Ogun State (BABCOCK)",
  "Baze University, Abuja (BAZE)",
  "Bells University of Technology, Ogun State (BELLSTECH)",
  "Benson Idahosa University, Benin (BIU)",
  "Bethel University, Calabar (BETHEL)",
  "Bowen University, Osun State (BOWEN)",
  "Caleb University, Lagos (CALEB)",
  "Centenary University, Abuja (CENTENARY)",
  "Chrisland University, Abeokuta (CHRISLAND)",
  "Christopher University, Mowe (CU-MOWE)",
  "Chukwuemeka Odumegwu Ojukwu University (COOU)",
  "Clifford University, Abia (CLIFFORD)",
  "Covenant University, Ogun State (CU)",
  "Crescent University, Abeokuta (CRESCENT)",
  "Dominican University, Ibadan (DUI)",
  "Fountain University, Osun (FOUNTAIN)",
  "Landmark University, Omu-Aran (LMU)",
  "Lead City University, Ibadan (LCU)",
  "Madonna University, Okija (MADONNA)",
  "McPherson University (MCU)",
  "Mountain Top University (MTU)",
  "Pan-Atlantic University, Lagos (PAU)",
  "Redeemer's University, Ede (RUN)",
  "Salem University, Lokoja (SALEM)",
  "Southwestern University, Oku Owa (SWU)",
  "Tansian University, Umunya (TANSIAN)",
  "Veritas University, Abuja (VERITAS)",
  "Wellspring University, Benin (WELLSPRING)",
  "Wesley University, Ondo (WESLEY)",
  // ── Colleges of Education ─────────────────────────────────────────────────
  "Adeyemi College of Education, Ondo State (ACE)",
  "Alvan Ikoku Federal College of Education, Owerri (AIFCE)",
  "College of Education, Akoka, Lagos (COE-AKOKA)",
  "College of Education, Akure (COE-AKURE)",
  "College of Education, Ado-Ekiti (COE-ADO)",
  "College of Education, Gusau (COE-GUSAU)",
  "College of Education, Ijebu-Ode (COE-IJEBU)",
  "College of Education, Ikere (COE-IKERE)",
  "College of Education, Katsina (COE-KATSINA)",
  "College of Education, Kontagora (COE-KONTAGORA)",
  "College of Education, Lagos (COE-LAGOS)",
  "College of Education, Minna (COE-MINNA)",
  "College of Education, Oron (COE-ORON)",
  "College of Education, Osogbo (COE-OSOGBO)",
  "College of Education, Owerri (COE-OWERRI)",
  "College of Education, Potiskum (COE-POTISKUM)",
  "College of Education, Warri (COE-WARRI)",
  "Emmanuel Alayande College of Education, Oyo (EACOED)",
  "Federal College of Education, Zaria (FCE-ZARIA)",
  "Tai Solarin University of Education, Ijagun (TASUED)",
  // ── Specialized Institutions ──────────────────────────────────────────────
  "Armed Forces Institute of Technology, Kaduna (AFIT)",
  "Institute of Management Technology, Enugu (IMT)",
  "Lagos Business School (LBS)",
  "Nigerian Defence Academy, Kaduna (NDA)",
  "Nigerian Institute of Journalism, Lagos (NIJ)",
  "Nigerian Police Academy, Wudil (POLAC)",
  "The African University of Science and Technology, Abuja (AUST)",
].sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase())) as unknown as readonly string[];

export const COMPANY_DEPARTMENTS = [
  "IT / Technology",
  "Finance & Accounts",
  "Engineering",
  "Operations",
  "Human Resources",
  "Marketing & Sales",
  "Customer Service",
  "Procurement",
  "Admin & Management",
  "Legal",
  "Production",
  "Quality Control",
  "Research & Development",
  "Health & Safety",
] as const;
